server:
  port: 8078

api:
  prefix: /api/v1

cors:
  allowed-origins: http://localhost:3000,http://localhost:8080
  allowed-methods: GET,POST,PATCH,PUT,DELETE

spring:
  application:
    name: mp-security
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db}
    username: ${postgres.user}
    password: ${postgres.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data-dev.sql
  banner:
    location: banner/banner-dev.txt
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG

postgres:
  host: localhost
  port: 5432
  db: mp-security
  user: postgres
  password: 12345

app:
  profile-server-url: http://localhost:8076
