spring:
  profiles:
    group:
      develop:
        - dev
        - swagger
        - redis
        - jwt
        - mail
      production:
        - prod
        - swagger
        - redis
        - jwt
        - mail
      test:
        - test
        - swagger
        - redis
        - jwt
        - mail
      postgres-test: # just a marker
      no-email-test: # just a marker
      default: production