app:
  mail:
    sender: test@gmail.com
    host: smtp.gmail.com
    port: 587
    username:
    password:

#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true