server:
  port: 8078

spring:
  application:
    name: mp-security
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    #    url: jdbc:h2:file:./db/t-auth
    username: test
    password: test
  banner:
    location: banner/banner-test.txt

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG
