server:
  port: 8078

api:
  prefix: /api/v1

spring:
  application:
    name: mp-security
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
#    url: jdbc:h2:file:./db/mp-security
    username: test
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data-test.sql
  banner:
    location: banner/banner-test.txt
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG

app:
  profile-server-url: http://localhost:8076