version: '3.7'
services:
  gateway-service:
    build: ./mp-gateway
    image: mp-gateway
    container_name: mp-gateway-cont
    ports:
      - "8080:8080"
      - "8081:8081"

  stats-service:
    build: ./mp-stats
    image: mp-stats
    container_name: mp-stats-cont
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:15.1-alpine
    container_name: mp-stats-db-cont
    ports:
      - "5777:5432"
    environment:
      - POSTGRES_DB=mp-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-service:
    build: ./mp-main
    image: mp-main
    container_name: mp-main-cont
    ports:
      - "7070:7070"
      - "7071:7071"
    depends_on:
      - main-db

  main-db:
    image: postgres:15.1-alpine
    container_name: mp-main-db-cont
    ports:
      - "5888:5432"
    environment:
      - POSTGRES_DB=mp-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root