version: '3.7'
services:
#  gateway-service:
#    build: ./mp-gateway
#    image: mp-gateway
#    container_name: mp-gateway-cont
#    ports:
#      - "8080:8080"
#      - "8081:8081"

  stats-service:
    build: ./mp-stats/server
    image: mp-stats
    container_name: mp-stats-cont
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - APP_DB_HOST=stats-db
      - APP_DB_PORT=27017
      - APP_DB_NAME=mp-stats
      - APP_DB_USERNAME=root
      - APP_DB_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=default

  stats-db:
    image: mongo:6.0.4
    container_name: mp-stats-db-cont
    ports:
      - "27070:27017"
    environment:
      MONGO_INITDB_DATABASE: mp-stats
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mp-stats/server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#      - ./db-saved-from-docker-container/mp-stats:/data/db

#  main-service:
#    build: ./mp-main
#    image: mp-main
#    container_name: mp-main-cont
#    ports:
#      - "7070:7070"
#      - "7071:7071"
#    depends_on:
#      - main-db

#  main-db:
#    image: postgres:15.1-alpine
#    container_name: mp-main-db-cont
#    ports:
#      - "5888:5432"
#    environment:
#      - POSTGRES_DB=mp-main
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#    volumes:
#      - /db/data/mp-main