server:
  port: 7070

spring:
  banner:
    location: banner/banner.txt

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG

app:
  format:
    date: yyyy-MM-dd
    date-time: yyyy-MM-dd HH:mm:ss
