name: MyPlace Postman Tests

on:
  pull_request:
    branches:
      - stats
      - security
      - profile
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build project images
        run: docker-compose build

      - name: Run project
        run: docker-compose up -d

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/stats' ]]; then
            newman run postman/MyPlace-mp-stats.postman_collection.json
          elif [[ ${{ github.ref }} == 'refs/heads/security' ]]; then
            newman run postman/MyPlace-mp-security.postman_collection.json
          elif [[ ${{ github.ref }} == 'refs/heads/profile' ]]; then
            newman run postman/MyPlace-mp-profile.postman_collection.json
          elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
            newman run postman/MyPlace-mp-stats.postman_collection.json
            newman run postman/MyPlace-mp-security.postman_collection.json
            newman run postman/MyPlace-mp-profile.postman_collection.json
          else
            echo "No specific Postman tests for this branch."
          fi

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: postman-report.xml
