version: '3.8'

services:

  profile-service:
    build: ../../mp-profile
    image: mp-profile
    container_name: mp-profile
    restart: unless-stopped
    env_file:
      - ./.env.profile.prod
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8076
      - POSTGRES_HOST=profile-db
      - POSTGRES_PORT=5432

  profile-db:
    image: postgres:14-alpine
    container_name: mp-profile-db
    env_file:
      - ./.env.profile.prod
    environment:
      - POSTGRES_PORT=5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
