version: '3.8'

# Use sudo docker-compose -f docker/profile/docker-compose-profile-prod.yml build/up/down

services:

  profile-service:
    build: ../../mp-profile
    image: mp-profile
    container_name: mp-profile
    restart: unless-stopped
    env_file:
      - ./.env.profile.prod
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8076
      - APP_DB_HOST=profile-db
      - APP_DB_PORT=5432
      - APP_DB_NAME=mp-profile

  profile-db:
    image: postgres:14-alpine
    container_name: mp-profile-db
    env_file:
      - ./.env.profile.prod
    environment:
      - POSTGRES_DB=mp-profile
      - POSTGRES_PORT=5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "mp-profile" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
#    volumes:
#      - ./myplace-app-saved-from-docker-container/db/profile/postgres-data:/var/lib/postgresql/data
