version: '3.8'
services:

# TODO Remove the external ports. Leave it only at the gateway service and databases

  # Use sudo docker-compose -f docker/profile/docker-compose-profile-test.yml build/up/down

  profile-service:
    build: ../../mp-profile
    image: mp-profile
    container_name: mp-profile
    restart: unless-stopped
    ports:
      - "8076:8076"
    environment:
      - SPRING_PROFILES_ACTIVE=test
