services:

  stats-service:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-dev.yml
      service: stats-service
    container_name: mp-stats-${CONTAINER_MARK:-std}
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-dev.yml
      service: stats-db
    container_name: mp-stats-db-${CONTAINER_MARK:-std}

  security-service:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-dev.yml
      service: security-service
    container_name: mp-security-${CONTAINER_MARK:-std}
    depends_on:
      security-redis-db:
        condition: service_healthy
      security-postgres-db:
        condition: service_healthy

  security-redis-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-dev.yml
      service: security-redis-db
    container_name: mp-security-redis-db-${CONTAINER_MARK:-std}

  security-postgres-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-dev.yml
      service: security-postgres-db
    container_name: mp-security-postgres-db-${CONTAINER_MARK:-std}

  profile-service:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-dev.yml
      service: profile-service
    container_name: mp-profile-${CONTAINER_MARK:-std}
    depends_on:
      profile-db:
         condition: service_healthy

  profile-db:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-dev.yml
      service: profile-db
    container_name: mp-profile-db-${CONTAINER_MARK:-std}
