version: '3.8'

services:

  stats-service:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-dev.yml
      service: stats-service
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-dev.yml
      service: stats-db

  security-service:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-dev.yml
      service: security-service
    depends_on:
      security-redis-db:
        condition: service_healthy
      security-postgres-db:
        condition: service_healthy

  security-redis-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-dev.yml
      service: security-redis-db

  security-postgres-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-dev.yml
      service: security-postgres-db

  profile-service:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-dev.yml
      service: profile-service
    depends_on:
      profile-db:
         condition: service_healthy

  profile-db:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-dev.yml
      service: profile-db
