services:

  gateway-service:
    profiles: [ "gateway", "full" ]
    extends:
      file: gateway/docker-compose-gateway-test.yml
      service: gateway-service
    container_name: mp-gateway-${CONTAINER_MARK:-std}
    networks:
      - myplace

  stats-service:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-test.yml
      service: stats-service
    container_name: mp-stats-${CONTAINER_MARK:-std}
    depends_on:
      stats-db:
        condition: service_healthy
    networks:
      - myplace

  stats-db:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-test.yml
      service: stats-db
    container_name: mp-stats-db-${CONTAINER_MARK:-std}
    networks:
      - myplace

  security-service:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-test.yml
      service: security-service
    container_name: mp-security-${CONTAINER_MARK:-std}
    depends_on:
      security-redis-db:
        condition: service_healthy
    networks:
      - myplace

  security-redis-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-test.yml
      service: security-redis-db
    container_name: mp-security-redis-db-${CONTAINER_MARK:-std}
    networks:
      - myplace

  profile-service:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-test.yml
      service: profile-service
    container_name: mp-profile-${CONTAINER_MARK:-std}
    networks:
      - myplace

networks:
  myplace:
    driver: bridge
