version: '3.8'

services:

  stats-service:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-prod.yml
      service: stats-service
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-prod.yml
      service: stats-db
    volumes:
      - ../db/docker-sync/stats-service/mongo/db:/data/db

  security-service:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-service
    depends_on:
      security-redis-db:
        condition: service_healthy
      security-postgres-db:
        condition: service_healthy

  security-redis-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-redis-db
    volumes:
      - ../db/docker-sync/security-service/redis/data:/data

  security-postgres-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-postgres-db
    volumes:
      - ../db/docker-sync/security-service/postgres/data:/var/lib/postgresql/data

  profile-service:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-prod.yml
      service: profile-service
    depends_on:
      profile-db:
        condition: service_healthy

  profile-db:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-prod.yml
      service: profile-db
    volumes:
      - ../db/docker-sync/profile-service/postgres/data:/var/lib/postgresql/data
