version: '3.8'

services:

  stats-service:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-prod.yml
      service: stats-service
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-prod.yml
      service: stats-db
    volumes:
      - stats_mongo_data:/data/db

  security-service:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-service
    depends_on:
      security-redis-db:
        condition: service_healthy
      security-postgres-db:
        condition: service_healthy

  security-redis-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-redis-db
    volumes:
      - security_redis_data:/data

  security-postgres-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-postgres-db
    volumes:
      - security_postgres_data:/var/lib/postgresql/data

  profile-service:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-prod.yml
      service: profile-service
    depends_on:
      profile-db:
        condition: service_healthy

  profile-db:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-prod.yml
      service: profile-db
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data

volumes:
  stats_mongo_data:
    name: myplace_stats_mongo_data
  security_redis_data:
    name: myplace_security_redis_data
  security_postgres_data:
    name: myplace_security_postgres_data
  profile_postgres_data:
    name: myplace_profile_postgres_data
