version: '3.8'

services:

  gateway-service:
    profiles: [ "gateway", "full" ]
    extends:
      file: gateway/docker-compose-gateway-prod.yml
      service: gateway-service
    container_name: mp-gateway-${CONTAINER_MARK:-std}
    networks:
      - myplace

  stats-service:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-prod.yml
      service: stats-service
    container_name: mp-stats-${CONTAINER_MARK:-std}
    depends_on:
      stats-db:
        condition: service_healthy
    networks:
      - myplace

  stats-db:
    profiles: [ "stats", "full" ]
    extends:
      file: stats/docker-compose-stats-prod.yml
      service: stats-db
    container_name: mp-stats-db-${CONTAINER_MARK:-std}
    volumes:
      - stats_mongo_data:/data/db
    networks:
      - myplace

  security-service:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-service
    container_name: mp-security-${CONTAINER_MARK:-std}
    depends_on:
      security-redis-db:
        condition: service_healthy
      security-postgres-db:
        condition: service_healthy
    networks:
      - myplace

  security-redis-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-redis-db
    container_name: mp-security-redis-db-${CONTAINER_MARK:-std}
    volumes:
      - security_redis_data:/data
    networks:
      - myplace

  security-postgres-db:
    profiles: [ "security", "full" ]
    extends:
      file: security/docker-compose-security-prod.yml
      service: security-postgres-db
    container_name: mp-security-postgres-db-${CONTAINER_MARK:-std}
    volumes:
      - security_postgres_data:/var/lib/postgresql/data
    networks:
      - myplace

  profile-service:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-prod.yml
      service: profile-service
    container_name: mp-profile-${CONTAINER_MARK:-std}
    depends_on:
      profile-db:
        condition: service_healthy
    networks:
      - myplace

  profile-db:
    profiles: [ "profile", "full" ]
    extends:
      file: profile/docker-compose-profile-prod.yml
      service: profile-db
    container_name: mp-profile-db-${CONTAINER_MARK:-std}
    volumes:
      - profile_postgres_data:/var/lib/postgresql/data
    networks:
      - myplace

volumes:
  stats_mongo_data:
    name: myplace_stats_mongo_data
  security_redis_data:
    name: myplace_security_redis_data
  security_postgres_data:
    name: myplace_security_postgres_data
  profile_postgres_data:
    name: myplace_profile_postgres_data

networks:
  myplace:
    driver: bridge
