version: '3.8'

services:

  security-service:
    build: ../../mp-security
    image: mp-security
    container_name: mp-security
    restart: unless-stopped
    env_file:
      - ./.env.security.prod
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8078
      - APP_PROFILE_SERVER_URL=http://profile-service:8076
      - APP_DB_HOST=security-postgres-db
      - APP_DB_PORT=5432
      - APP_DB_NAME=mp-security
      - REDIS_HOST=security-redis-db
      - REDIS_PORT=6379

  security-redis-db:
    image: redis:latest
    container_name: mp-security-redis-db
    environment:
      - REDIS_PORT=6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  security-postgres-db:
    image: postgres:14-alpine
    container_name: mp-security-postgres-db
    env_file:
      - ./.env.security.prod
    environment:
      - POSTGRES_DB=mp-security
      - POSTGRES_PORT=5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "mp-security" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./myplace-app-saved-from-docker-container/db/security/postgres-data:/var/lib/postgresql/data

