version: '3.8'

services:

  security-service:
    build: ../../mp-security
    image: mp-security
    container_name: mp-security
    restart: unless-stopped
    env_file:
      - ./.env.security.prod
    environment:
      - SPRING_PROFILES_ACTIVE=production${SECURITY_ADDITIONAL_SPRING_PROFILES:-""}
      - SERVER_PORT=8078
      - APP_PROFILE_SERVER_URL=http://profile-service:8076/api/v1
      - APP_DB_HOST=security-postgres-db
      - APP_DB_PORT=5432
      - APP_DB_NAME=${SECURITY_POSTGRES_DB}
      - APP_DB_USERNAME=${SECURITY_POSTGRES_USER}
      - APP_DB_PASSWORD=${SECURITY_POSTGRES_PASSWORD}
      - REDIS_HOST=security-redis-db
      - REDIS_PORT=6379

  security-redis-db:
    image: redis:latest
    container_name: mp-security-redis-db
    environment:
      - REDIS_PORT=6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  security-postgres-db:
    image: postgres:14-alpine
    container_name: mp-security-postgres-db
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${SECURITY_POSTGRES_DB}
      - POSTGRES_USER=${SECURITY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SECURITY_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
