spring:
  profiles:
    group:
      develop:
        - dev
        - app
        - swagger
      production:
        - prod
        - app
        - swagger
      test:
        - test
        - app
        - swagger
      default: production