app:
  mp:
    security:
      label: security
      url: http://localhost:8078/api/v1
    profile:
      label: profile
      url: http://localhost:8076/api/v1
    stats:
      label: stats
      url: http://localhost:9090/api/v1
  http:
    connect-timeout: 3s
    read-timeout: 7s