spring:
  banner:
    location: banner/banner-dev.txt
  data:
    mongodb:
      host: ${mongo.host}
      port: ${mongo.port}
      database: ${mongo.initdb.database}
      username: ${mongo.initdb.root.username}
      password: ${mongo.initdb.root.password}
      authentication-database: admin

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG
