spring:
  banner:
    location: banner/banner-test.txt
  data:
    mongodb:
      host: ${app.db.host}
      port: ${app.db.port}
      database: mp-stats-test
      authentication-database: admin

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG
