spring:
  banner:
    location: banner/banner-test.txt
  data:
    mongodb:
      host: ${mongo.host}
      port: ${mongo.port}
      database: ${mongo.initdb.database}
      authentication-database: admin

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG
