server:
  port: 9090

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs
    enabled: true

mongo:
  host: localhost
  port: 27017
  initdb:
    database: mp-stats
    root:
      username: root
      password: root

