spring:
  profiles:
    group:
      develop:
        - dev
        - common
        - swagger
      production:
        - prod
        - common
        - swagger
      test:
        - test
        - common
        - swagger
      default: production