spring:
  banner:
    location: banner/banner-test.txt
  data:
    mongodb:
      host: ${app.db.host}
#      port: ${app.db.port}
      port: 27070
      database: ${app.db.name}
      username: ${app.db.username}
      password: ${app.db.password}
      authentication-database: admin

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG
