services:

  gateway-service:
    build: ../../mp-gateway
    image: mp-gateway
    container_name: mp-gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
