version: '3.8'

# Use sudo docker-compose -f docker/stats/docker-compose-stats-test.yml build/up/down

services:

  stats-service:
    build: ../../mp-stats/server
    image: mp-stats
    container_name: mp-stats
    restart: unless-stopped
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - APP_DB_HOST=stats-db
      - APP_DB_PORT=27017
      - APP_DB_NAME=mp-stats
      - APP_DB_USERNAME=root
      - APP_DB_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=production # Here is the production profile for the correct configuration of Mongo in Spring

  stats-db:
    image: mongo:6.0.4
    container_name: mp-stats-db
    ports:
      - "27070:27017"
    environment:
      MONGO_INITDB_DATABASE: mp-stats
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      #      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      #      test: echo "db.runCommand({serverStatus:1}).ok" | mongosh admin -u "root" -p "root" --quiet | grep 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
#    volumes:
#      - ../../mp-stats/server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
