version: '3.8'

services:

  stats-service:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-service
    image: mp-stats
    container_name: mp-stats
    restart: unless-stopped
    env_file:
      - ./.env.stats.prod
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=9090
      - APP_DB_HOST=stats-db
      - APP_DB_PORT=27017
      - APP_DB_NAME=mp-stats

  stats-db:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-mongo-db
    image: mp-stats-mongo-db
    container_name: mp-stats-db
    env_file:
      - ./.env.stats.prod
    environment:
      - MONGO_INITDB_DATABASE=mp-stats
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./myplace-app-saved-from-docker-container/db/stats/mongo-data:/data/db
