version: '3.8'

# Use sudo docker-compose -f docker/stats/docker-compose-stats-test.yml build/up/down

services:

  stats-service:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-service
    image: mp-stats
    container_name: mp-stats
    restart: unless-stopped
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - APP_DB_HOST=stats-db
      - APP_DB_PORT=27017
      - SPRING_PROFILES_ACTIVE=test

  stats-db:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-mongo-db
    container_name: mp-stats-db
    ports:
      - "27070:27017"
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
