version: '3.8'

services:

  stats-service:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-service
    image: mp-stats
    container_name: mp-stats
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=9090
      - APP_DB_HOST=stats-db
      - APP_DB_PORT=27017
      - APP_DB_NAME=${STATS_MONGO_INITDB_DATABASE}
      - APP_DB_USERNAME=${STATS_MONGO_INITDB_ROOT_USERNAME}
      - APP_DB_PASSWORD=${STATS_MONGO_INITDB_ROOT_PASSWORD}

  stats-db:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-mongo-db
    image: mp-stats-mongo-db
    container_name: mp-stats-db
    environment:
      - MONGO_INITDB_DATABASE=${STATS_MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${STATS_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${STATS_MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD","mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
