version: '3.8'

# Use sudo docker-compose -f docker/stats/docker-compose-stats-prod.yml build/up/down

services:

  stats-service:
    build: ../../mp-stats/server
    image: mp-stats
    container_name: mp-stats
    restart: unless-stopped
#    ports:
#      - "9090"
#      - "9091:9091"
    environment:
#      - SPRING_PROFILES_ACTIVE=production
#      - APP_DB_HOST=stats-db
#      - APP_DB_PORT=27017
#      - APP_DB_NAME=mp-stats
#      - APP_DB_USERNAME=root
#      - APP_DB_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - APP_DB_HOST=${APP_DB_HOST}
      - APP_DB_PORT=${APP_DB_PORT}
      - APP_DB_NAME=${APP_DB_NAME}
      - APP_DB_USERNAME=${APP_DB_USERNAME}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}

  stats-db:
    image: mongo:6.0.4
    container_name: mp-stats-db
    ports:
      - "${STATS_DB_PORT}:27017"
    environment:
#      MONGO_INITDB_DATABASE: mp-stats
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
#    volumes:
#      - ../../mp-stats/server/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # Сделать копирование и DockerFile^ COPY ../../mp-stats/server/mongo-init.js /docker-entrypoint-initdb.d/mongo-init.js
#      - ./myplace-app-saved-from-docker-container/db/stats/mongo-data:/data/db
