version: '3.8'

services:

  stats-service:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-service
    image: mp-stats
    container_name: mp-stats
    restart: unless-stopped
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - SPRING_PROFILES_ACTIVE=develop
      - APP_DB_HOST=stats-db
      - APP_DB_PORT=27017
      - APP_DB_NAME=mp-stats
      - APP_DB_USERNAME=root
      - APP_DB_PASSWORD=root

  stats-db:
    build:
      context: ../../mp-stats/server
      dockerfile: Dockerfile-mongo-db
    image: mp-stats-mongo-db
    container_name: mp-stats-db
    ports:
      - "27070:27017"
    environment:
      MONGO_INITDB_DATABASE: mp-stats
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 5s
