server:
  port: 8076

api:
  prefix: /api/v1

spring:
  application:
    name: mp-profile
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
#    url: jdbc:h2:file:./db/mp-profile
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        webAllowOthers: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
#        use_sql_comments: true
  banner:
    location: banner/banner-test.txt
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG
#    org.hibernate.type: TRACE
