server:
  port: 8076

api:
  prefix: /api/v1

spring:
  application:
    name: mp-profile
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.db}
    username: ${postgres.user}
    password: ${postgres.password}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  banner:
    location: banner/banner-dev.txt
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG
    org:
      hibernate:
        SQL: debug
#        type: trace

postgres:
  host: localhost
  port: 5432
  db: mp-profile
  user: postgres
  password: 12345
