spring:
  profiles:
    group:
      develop:
        - dev
        - swagger
        - liquibase
      production:
        - prod
        - swagger
        - liquibase
      test:
        - test
        - swagger
        - liquibase
      default: production