server:
  port: 8076

spring:
  application:
    name: mp-profile
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${app.db.host}:${app.db.port}/${app.db.name}
    username: ${app.db.username}
    password: ${app.db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  banner:
    location: banner/banner.txt
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

logging:
  level:
    ru.pavbatol: DEBUG
    org.springframework.web: DEBUG

app:
  db:
    host: localhost
    port: 5432
    name: mp-profile
    username: postgres
    password: 12345